import unittest
from unittest.mock import patch, MagicMock
from enge.utils.opt_manager import parsed_opts

# Inject mock before importing module that might use parsed_opts
mock_opts = MagicMock()
# Setup default mock values for options used in SubmitTest.__init__
mock_opts.testing_farm_endpoint.log_artifact_baseurl = "http://logs.example.com"
mock_opts.testing_farm_endpoint.api_endpoint_url = "http://api.example.com"
mock_opts.cli_args.auto_tag = False
mock_opts.cli_args.set_tag = None
mock_opts.cli_args.dryrun = False
mock_opts.environment_variables = {}
mock_opts.tmt_context = {}
mock_opts.architectures = ["x86_64"]

parsed_opts.set(mock_opts)

from enge.dispatch.tf_send_request import SubmitTest


class TestSubmitTest(unittest.TestCase):
    def setUp(self):
        # Reset mock opts for each test if needed, but usually the global one is fine
        # or we can patch attributes on the injected mock
        pass

    def test_payload_structure(self):
        """Verify the payload structure generated by build_payload"""
        submit = SubmitTest()
        submit.api_key = "fake-key"
        submit.compose = "RHEL-9.0"
        submit.tests_git_url = "https://github.com/example/tests"
        submit.tests_git_ref = "main"
        submit.plan = "test-plan"
        submit.tmt_distro = "rhel-9"

        header, payload = submit.build_payload()

        # Check header
        self.assertEqual(header, {"Authorization": "Bearer fake-key"})

        # Check essential payload fields
        self.assertIn("test", payload)
        self.assertIn("environments", payload)

        # Check FMF struct
        fmf = payload["test"]["fmf"]
        self.assertEqual(fmf["url"], "https://github.com/example/tests")
        self.assertEqual(fmf["ref"], "main")
        self.assertEqual(fmf["name"], "test-plan")

        # Check Environment
        env = payload["environments"][0]
        self.assertEqual(env["arch"], "x86_64")
        self.assertEqual(env["os"]["compose"], "RHEL-9.0")
        self.assertEqual(env["tmt"]["context"]["distro"], "rhel-9")

    def test_payload_with_artifacts(self):
        """Verify artifacts are correctly added to payload"""
        submit = SubmitTest()
        submit.add_artifact("12345", "fedora-copr-build", ["pkg1", "pkg2"])

        _, payload = submit.build_payload()

        artifacts = payload["environments"][0]["artifacts"]
        self.assertEqual(len(artifacts), 1)
        self.assertEqual(artifacts[0]["id"], "12345")
        self.assertEqual(artifacts[0]["type"], "fedora-copr-build")
        self.assertEqual(artifacts[0]["packages"], ["pkg1", "pkg2"])

    def test_payload_with_env_vars(self):
        """Verify environment variables are correctly passed"""
        submit = SubmitTest()
        # Set specific env vars for this test
        submit.set_environment_variables = {"TEST_VAR": "value"}

        _, payload = submit.build_payload()

        variables = payload["environments"][0]["variables"]
        self.assertEqual(variables["TEST_VAR"], "value")

    @patch("enge.dispatch.tf_send_request.http_post")
    def test_send_request_success(self, mock_post):
        """Test successful request submission"""
        submit = SubmitTest()
        submit.api_key = "fake-key"

        # Mock successful response
        mock_response = MagicMock()
        mock_response.json.return_value = {"id": "task-123"}
        mock_response.status_code = 200
        mock_post.return_value = mock_response

        # Prevent file operations in record_task_ids
        submit.record_task_ids = MagicMock()
        # Prevent printing
        submit.assess_summary_message = MagicMock(return_value="Summary")

        payload = {"dummy": "payload"}
        header = {"Auth": "key"}

        submit.send_request(payload, header)

        mock_post.assert_called_once_with(
            "http://api.example.com",
            json=payload,
            headers=header,
            timeout=60,  # Default timeout
        )
        self.assertEqual(submit.log_artifact_url, "http://logs.example.com/task-123")

    def test_dry_run_does_not_send_request(self):
        """Verify dry run prints payload but doesn't send request"""
        # Temporarily set dryrun to True
        mock_opts.cli_args.dryrun = True

        try:
            submit = SubmitTest()
            with patch("enge.dispatch.tf_send_request.http_post") as mock_post:
                submit.send_request({}, {})
                mock_post.assert_not_called()
        finally:
            mock_opts.cli_args.dryrun = False


if __name__ == "__main__":
    unittest.main()
